# Generated by Django 5.1.2 on 2024-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('propertyId', models.IntegerField()),
                ('requestDate', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
