# Generated by Django 5.1.2 on 2024-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('propertyId', models.IntegerField()),
                ('tenantId', models.IntegerField()),
                ('submissionDate', models.DateField()),
                ('starRating', models.IntegerField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
